# Generated by Django 5.2.10 on 2026-01-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do exemplo', max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do exemplo', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examples', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Example',
                'verbose_name_plural': 'Examples',
                'db_table': 'reserveme_example',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='reserveme_e_created_be550d_idx'), models.Index(fields=['created_by'], name='reserveme_e_created_2fb7c5_idx'), models.Index(fields=['name'], name='reserveme_e_name_7c7bcf_idx')],
            },
        ),
    ]
