# Generated by Django 5.2.10 on 2026-01-14 23:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'Já existe um usuário com este email.'}, max_length=254, unique=True, verbose_name='email address')),
                ('cpf', models.CharField(help_text='Formato: 999.999.999-99', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 999.999.999-99', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, help_text='Formato: (99) 99999-9999', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: (99) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('avatar', models.ImageField(blank=True, help_text='Imagem de perfil do usuário', null=True, upload_to='avatars/%Y/%m/', verbose_name='Avatar')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('staff', 'Staff'), ('customer', 'Cliente')], default='customer', help_text='Papel do usuário no sistema', max_length=20, verbose_name='Papel')),
                ('is_approved', models.BooleanField(default=False, help_text='Usuário foi aprovado manualmente por um admin', verbose_name='Aprovado')),
                ('email_verified', models.BooleanField(default=False, help_text='Usuário verificou seu email', verbose_name='Email Verificado')),
                ('email_verification_token', models.CharField(blank=True, max_length=100, verbose_name='Token de Verificação de Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'reserveme_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do exemplo', max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do exemplo', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examples', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Example',
                'verbose_name_plural': 'Examples',
                'db_table': 'reserveme_example',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='reserveme_u_email_14ce6f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['cpf'], name='reserveme_u_cpf_73547a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='reserveme_u_role_9f40cd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='reserveme_u_created_06cd93_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_approved', 'email_verified'], name='reserveme_u_is_appr_6e0e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='examplemodel',
            index=models.Index(fields=['-created_at'], name='reserveme_e_created_be550d_idx'),
        ),
        migrations.AddIndex(
            model_name='examplemodel',
            index=models.Index(fields=['created_by'], name='reserveme_e_created_2fb7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='examplemodel',
            index=models.Index(fields=['name'], name='reserveme_e_name_7c7bcf_idx'),
        ),
    ]
