# Generated by Django 5.2.10 on 2026-01-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserveme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='reserveme_u_email_14ce6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='reserveme_u_cpf_73547a_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='reserveme_u_role_9f40cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='reserveme_u_created_06cd93_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='reserveme_u_is_appr_6e0e9d_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
