# Generated by Django 5.2.10 on 2026-01-17 02:09

from django.db import migrations, models


def clean_cpf_values(apps, schema_editor):
    """Remove caracteres especiais dos CPFs existentes."""
    User = apps.get_model('reserveme', 'User')
    for user in User.objects.all():
        if user.cpf:
            # Remove todos os caracteres não numéricos
            cpf_clean = ''.join(filter(str.isdigit, user.cpf))
            user.cpf = cpf_clean
            user.save(update_fields=['cpf'])


def reverse_clean_cpf(apps, schema_editor):
    """Não é possível reverter a limpeza de CPFs."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reserveme', '0002_remove_user_reserveme_u_email_14ce6f_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_cpf_values, reverse_clean_cpf),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
