# Generated by Django 5.2.10 on 2026-01-17 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveme', '0003_clean_cpf_and_alter_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Hotel')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do hotel', verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, help_text='Logo do hotel', null=True, upload_to='hotels/logos/%Y/%m/', verbose_name='Logo')),
                ('endereco', models.CharField(help_text='Endereço completo do hotel', max_length=500, verbose_name='Endereço')),
                ('telefone', models.CharField(help_text='Formato: (99) 99999-9999', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: (99) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Email de contato do hotel', max_length=254, verbose_name='Email')),
                ('horario_checkin', models.TimeField(help_text='Horário padrão para check-in', verbose_name='Horário de Check-in')),
                ('horario_checkout', models.TimeField(help_text='Horário padrão para check-out', verbose_name='Horário de Check-out')),
                ('is_active', models.BooleanField(default=True, help_text='Hotel está ativo no sistema', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotéis',
                'ordering': ['nome'],
            },
        ),
    ]
