# Generated by Django 5.2.10 on 2026-01-18 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveme', '0004_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número ou identificação do quarto (ex: 101, A1, etc)', max_length=10, verbose_name='Número do Quarto')),
                ('tipo', models.CharField(choices=[('single', 'Solteiro'), ('double', 'Casal'), ('twin', 'Twin (2 Solteiros)'), ('triple', 'Triplo'), ('suite', 'Suíte'), ('deluxe', 'Suíte Deluxe'), ('presidential', 'Suíte Presidencial')], default='double', max_length=20, verbose_name='Tipo de Quarto')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do quarto', verbose_name='Descrição')),
                ('capacidade', models.PositiveIntegerField(default=2, help_text='Número máximo de hóspedes', verbose_name='Capacidade')),
                ('preco_diaria', models.DecimalField(decimal_places=2, help_text='Valor da diária em reais', max_digits=10, verbose_name='Preço da Diária')),
                ('tem_ar_condicionado', models.BooleanField(default=True, verbose_name='Ar Condicionado')),
                ('tem_wifi', models.BooleanField(default=True, verbose_name='Wi-Fi')),
                ('tem_tv', models.BooleanField(default=True, verbose_name='TV')),
                ('tem_frigobar', models.BooleanField(default=True, verbose_name='Frigobar')),
                ('tem_banheira', models.BooleanField(default=False, verbose_name='Banheira')),
                ('tem_varanda', models.BooleanField(default=False, verbose_name='Varanda')),
                ('foto_principal', models.ImageField(blank=True, help_text='Foto principal do quarto', null=True, upload_to='rooms/photos/%Y/%m/', verbose_name='Foto Principal')),
                ('is_active', models.BooleanField(default=True, help_text='Quarto disponível para reservas', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='reserveme.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'ordering': ['hotel', 'numero'],
                'unique_together': {('hotel', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(help_text='Código único para identificar a reserva', max_length=20, unique=True, verbose_name='Código da Reserva')),
                ('data_checkin', models.DateField(verbose_name='Data de Check-in')),
                ('data_checkout', models.DateField(verbose_name='Data de Check-out')),
                ('numero_hospedes', models.PositiveIntegerField(help_text='Quantidade de pessoas', verbose_name='Número de Hóspedes')),
                ('numero_diarias', models.PositiveIntegerField(help_text='Quantidade de noites', verbose_name='Número de Diárias')),
                ('preco_diaria', models.DecimalField(decimal_places=2, help_text='Valor da diária no momento da reserva', max_digits=10, verbose_name='Preço da Diária')),
                ('preco_total', models.DecimalField(decimal_places=2, help_text='Valor total da reserva', max_digits=10, verbose_name='Preço Total')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('checked_in', 'Check-in Realizado'), ('checked_out', 'Check-out Realizado'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Observações ou requisitos especiais', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Check-in realizado em')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Check-out realizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reserveme.room', verbose_name='Quarto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
